import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { DarkModeToggle } from "@/components/dark-mode-toggle";
import Header from "@/components/header";
const inter = Inter({ subsets: ["latin"] });
// Remove the server-side injected CSS.
// if (document.body.getAttribute("style") === "") {
//   document.body.removeAttribute("style");
// }
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {/* <SignUpFrom /> */}

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
